# Study of Numpy Library

## Vishvam Delwadiya

## PRN: - 25070123124

In [29]:
#Declaration of Numpy
import numpy as np

a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3] , [4,5,6]])
print(a)
print(b)
display(a.dtype)
print(b * 2)
print(a + 5)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]


dtype('int64')

[[ 2  4  6]
 [ 8 10 12]]
[  6  15  25  35  45  55 505]


In [8]:
#Dimension of Arrya
print(a.ndim)
print(b.ndim)

1
2


In [19]:
print(a.shape)
print(b.shape)


(7,)
(2, 3)


In [14]:
print(a.dtype)

int64


In [20]:
# In-Built functions using Numpy
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
print(np.arange(1,11,2))

[1 3 5 7 9]


In [27]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [33]:
np.mean(a)

np.float64(93.0)

In [32]:
np.median(a)

np.float64(30.0)

In [35]:
np.max(a)

np.int64(500)

In [36]:
np.min(a)

np.int64(1)

In [37]:
np.sum(a)

np.int64(651)